events {
    worker_connections 1024;
}

http {
    upstream auth_service {
        server pibo-auth-service:3000;
    }

    upstream frontend {
        server pibo-frontend-web:3000;
    }

    server {
        listen 80;
        server_name pibo.app www.pibo.app localhost;

        # Frontend Proxy
        location / {
            proxy_pass http://frontend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # API Routes
        location /api/auth {
            rewrite ^/api/auth/(.*) /$1 break;
            proxy_pass http://auth_service;
            proxy_set_header Host $host;
        }
    }
}
