name: Pibo ERP CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [
          apps/pibo-auth-service,
          apps/pibo-fiscal-service,
          apps/pibo-vendas-service,
          apps/pibo-estoque-service,
          apps/pibo-crm-service,
          apps/pibo-financeiro-service,
          apps/pibo-workflow-service,
          apps/pibo-contratos-service,
          apps/pibo-contratos-service,
          apps/pibo-config-service,
          apps/pibo-compras-service,
          apps/pibo-frontend-web
        ]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Dependencies
      working-directory: ${{ matrix.service }}
      run: npm ci

    - name: Build
      working-directory: ${{ matrix.service }}
      run: npm run build
